services:
  db:
    image: postgres:15.1-alpine3.17
    restart: unless-stopped
    command: -p ${DB_PORT:-5432}
    environment:
      POSTGRES_DB: ${DB_NAME:-blog-task}
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - ./data/db:/var/lib/postgresql/data\

  migration:
    image: backend-api
    build: .
    command: ["npm", "run", "migration"]
    depends_on:
      - db

  api:
    restart: unless-stopped
    build: .
    ports:
      - "$PORT:$PORT"
    depends_on:
      - db
      - migration