export const PERMISSION_METADATA_KEY = 'PERMISSION_METADATA_KEY';

export enum Permissions {
  CREATE_POST = 'CREATE_POST',
  READ_USER_POST = 'READ_USER_POST',
  READ_PUBLIC_POST = 'READ_PUBLIC_POST',
  UPDATE_USER_POST = 'UPDATE_USER_POST',
  DELETE_USER_POST = 'DELETE_USER_POST',
  DELETE_ANY_PUBLIC_POST = 'DELETE_ANY_PUBLIC_POST',
}

export enum Roles {
  ADMIN = 'ADMIN',
  BLOGGER = 'BLOGGER',
}
